// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dffhhforfwhgzdlrfzpc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmZmhoZm9yZndoZ3pkbHJmenBjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEwMzk1NzQsImV4cCI6MjA3NjYxNTU3NH0.XlGqFyK12HiQLnVoBPgzA1OXKM9c-K3gvqxvVFM8bFM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});